# GitHub Actions docs
# https://help.github.com/en/articles/about-github-actions
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: CI

on: [push]

jobs:

  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        check-latest: true
    - name: Install dependencies
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
    - name: yarn install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: yarn install
    - name: Lint
      run: ./node_modules/.bin/ng lint

  security:
    name: security
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        check-latest: true
    - name: Install dependencies
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
    - name: yarn install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: yarn install
    - name: Security audit of dependencies
      run: yarn audit

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        check-latest: true
    - name: Install dependencies
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: "**/node_modules"
        key: ${{ runner.os }}-node-modules-${{ hashFiles('yarn.lock') }}
    - name: yarn install
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: yarn install
    - name: Build
      run: ./node_modules/.bin/ionic build
